-- db_schema.sql

CREATE TABLE IF NOT EXISTS usuarios (
  id SERIAL PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  rol VARCHAR(20) NOT NULL DEFAULT 'empleado'
);

CREATE TABLE IF NOT EXISTS solicitudes (
  id SERIAL PRIMARY KEY,
  asunto VARCHAR(255) NOT NULL,
  descripcion TEXT NOT NULL,
  usuario_id INTEGER REFERENCES usuarios(id) ON DELETE CASCADE
);
